[package]
name = "scum"
version = "0.2.0"
edition = "2021"

[dependencies]
rustyline = "15.0.0"
peg = "0.8.4"
thiserror = "2.0.11"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "none"

[profile.dev]
debug = 0
