[package]
name = "scum"
version = "0.3.0"
edition = "2024"

[dependencies]
peg = "0.8.4"
rustyline = "15.0.0"
thiserror = "2.0.11"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "none"

[profile.dev]
debug = 0
