[package]
name = "scum"
version = "0.3.2"
edition = "2024"

[dependencies]
peg = "0.8.5"
rustyline = "17.0.1"
thiserror = "2.0.16"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[profile.dev]
debug = 0
