name: scum
version: 0.1.0.0
license: MIT
maintainer: Graham Enos <graham.enos@gmail.com>
github: genos/scum
synopsis: Write me a Scheme-ish
description: See README at <https://github.com/genos/scum#readme>
category: Math
extra-source-files:
  - README.md

ghc-options: -Wall -Wextra

library:
  source-dirs: src
  exposed-modules: Scum
  dependencies:
    - base ^>=4.17.0.0
    - containers ^>= 0.6.7
    - megaparsec ^>= 9.3.0
    - text ^>= 2.0.2
    - transformers ^>= 0.6.1.0

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - base ^>=4.17.0.0
    - scum
    - optparse-applicative ^>= 0.17.0.0

tests:
  scum-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - base ^>=4.17.0.0
      - scum
      - hedgehog ^>= 1.2
