[package]
name = "scum-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.12.1"
once_cell = "1.17.1"
regex = "1.7.3"
snailquote = "0.3.1"
thiserror = "1.0.40"

[dev-dependencies]
proptest = "1.1.0"
rstest = "0.17.0"
